// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktjvkwkqcsmtjxgfuizd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0anZrd2txY3NtdGp4Z2Z1aXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MzM2ODIsImV4cCI6MjA3MTMwOTY4Mn0.ctBvR-CkRoBJkbq5r1yMgPjscavW1oxjOMwtCapK3u0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});